services:
  asl3_setup:
    build: .
    container_name: allstarlink3
    volumes:
      - ./asl3:/asl3
      - ./asterisk_conf:/etc/asterisk
      - ./asterisk_cust_sounds:/usr/local/share/asterisk/sounds
    privileged: true
    restart: unless-stopped
